#!/bin/bash

namespace=""
secret_names=""

while [ $# -gt 0 ]; do
  key="$1"

  case $key in
    -n|--namespace)
      namespace="-n $2"
      shift
      shift
      ;;
    -h|--help)
      echo "Usage: $0 [-n|--namespace NAMESPACE] [SECRET_NAME]"
      echo "  -n|--namespace NAMESPACE: namespace to search for secrets"
      echo "  SECRET_NAME: name of the secret(s) to decode"
      exit 0
      ;;
    *)
      secret_names="$secret_names $1"
      shift
      ;;
  esac
done

nr_of_secrets=$(echo "$secret_names" | wc -w)
selector_string="$secret_names $namespace"

if [ "$nr_of_secrets" -ne 1 ]; then
  kubectl get secrets $selector_string -o json | jq -r '.items[] | select(.data != null) | "\(.metadata.name)\n\(.data | with_entries(.value |= @base64d))"' | while read -r name; do
    read -r data
    echo "---- $name ----"
    echo "$data" | yq -P
  done
else
  kubectl get secret $selector_string -ojson | jq -r '. | select(.data != null) | "\(.metadata.name)\n\(.data | with_entries(.value |= @base64d))"' | while read -r name; do
    read -r data
    echo "---- $name ----"
    echo "$data" | yq -P
  done
fi
